parameters:
    kuma_voting_default_value: 1

kunstmaan_voting:
    actions:
        up_vote:
            default_value: %kuma_voting_default_value%
        down_vote:
            default_value: -%kuma_voting_default_value%
        facebook_like:
            default_value: %kuma_voting_default_value%
        facebook_send:
            default_value: %kuma_voting_default_value%
        linkedin_share:
            default_value: %kuma_voting_default_value%
