parameters:
#    kunstmaan_voting_list.example.class: Kunstmaan\VotingBundle\Example

services:
#    kunstmaan_voting_list.example:
#        class: %kunstmaan_voting_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    ## FACEBOOK LIKE

    kunstmaan_voting.facebooklike:
        class: Kunstmaan\VotingBundle\EventListener\Facebook\FacebookLikeEventListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kunstmaan_voting.facebookLike, method: onFacebookLike }

    kunstmaan_voting.helper.facebook.like:
        class: Kunstmaan\VotingBundle\Helper\Facebook\FacebookLikeHelper
        arguments: ["@doctrine.orm.entity_manager"]

    ## FACEBOOK SEND


    kunstmaan_voting.facebooksend:
        class: Kunstmaan\VotingBundle\EventListener\Facebook\FacebookSendEventListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kunstmaan_voting.facebookSend, method: onFacebookSend }

    kunstmaan_voting.helper.facebook.send:
        class: Kunstmaan\VotingBundle\Helper\Facebook\FacebookSendHelper
        arguments: ["@doctrine.orm.entity_manager"]