parameters:
#    kunstmaan_vorting_list.example.class: Kunstmaan\VotingBundle\Example

services:
#    kunstmaan_voting_list.example:
#        class: %kunstmaan_voting_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]